services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    SimpleSkypeBot\:
        resource: './../../*'
        exclude: './../../{Model,Migrations,Tests,Kernel.php}'

    SimpleSkypeBot\Controller\:
        resource: './../../Controller'
        tags: ['controller.service_arguments']

    SimpleSkypeBot\Command\SendMessageCommand:
        arguments:
          - null
          - '@SimpleSkypeBot\Service\SkypeBotManager'
          - '@doctrine.orm.entity_manager'
          - '%simply_skype_bot.user_class%'
        tags:
            - { name: 'console.command' }

    SimpleSkypeBot\Service\SkypeBotManager:
        arguments:
          - '@SimpleSkypeBot\Service\SkypeApiClient'
          - '@doctrine.orm.entity_manager'
          - '@logger'
          - '%simply_skype_bot.user_class%'
          - '%simply_skype_bot.token_class%'
    SimpleSkypeBot\Service\SkypeApiClient:
        arguments:
            - '@logger'
            - '%simply_skype_bot.login_endpoint%'
            - '%simply_skype_bot.connector_endpoint%'
            - '%simply_skype_bot.client_id%'
            - '%simply_skype_bot.client_secret%'
